general:
  label: 基本设置
  items:
    logo:
      name: logo
      label: Logo 展示
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    logo_width:
      name: logo_width
      label: Logo 长度
      type: text
      default: 40
    logo_height:
      name: logo_width
      label: Logo 宽度
      type: text
      default: 40
    copyright:
      name: copyright
      label: 底部版权信息
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    board:
      name: board
      label: 站点公告
      type: textarea
      default: <p>欢迎交流与分享经验!</p>
style:
  label: 样式设置
  items:
    skin:
      name: skin
      label: 主题颜色
      type: select
      default: ''
      options:
        - value: ''
          label: 无
        - value: theme-black
          label: theme-black
        - value: theme-blue
          label: theme-blue
        - value: theme-green
          label: theme-green
        - value: theme-purple
          label: theme-purple
    layout:
      name: layout
      label: 布局方式
      type: select
      default: main-center
      options:
        - value: main-center
          label: main-center
        - value: main-left
          label: main-left
        - value: main-right
          label: main-right
    toc:
      name: toc
      label: 是否开启文章章节目录导航
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    menu_highlight:
      name: menu_highlight
      label: 是否开启当前菜单高亮显示
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    thumbnail:
      name: thumbnail
      label: 文章缩略图
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    excerpt_link:
      name: excerpt_link
      label: excerpt_link
      type: text
      default: Read More
    menu_icons:
      name: menu_icons
      label: 是否启用导航菜单图标
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    pagination_number:
      name: pagination_number
      label: 分页数码
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    pagination_prev_alwayShow:
      name: pagination_prev_alwayShow
      label: 上一页
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    pagination_next_alwayShow:
      name: pagination_next_alwayShow
      label: 下一页
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
sidebar:
  label: 侧边栏
  items:
    sidebar_board:
      name: sidebar_board
      label: 侧边栏公告
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_category:
      name: sidebar_category
      label: 侧边栏分类
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_tag:
      name: sidebar_tag
      label: 侧边栏标签
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_tagcloud:
      name: sidebar_tagcloud
      label: 侧边栏标签云
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_archive:
      name: sidebar_archive
      label: 侧边栏归档
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_recent_posts:
      name: sidebar_recent_posts
      label: 侧边栏最近文章
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
other:
  label: 其他
  items:
    fancybox:
      name: fancybox
      label: Fancybox 插件
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    donate_enable:
      name: donate_enable
      label: 开启打赏
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    donate_wechatpay:
      name: donate_wechatpay
      label: 微信二维码链接
      type: text
    donate_alipay:
      name: donate_alipay
      label: 支付宝二维码链接
      type: text
    github_username:
      name: github_username
      lable: Github 用户名
      type: text
    douban_user:
      name: douban_user
      lable: 豆瓣用户名
      type: text
    douban_start:
      name: douban_start
      lable: douban_start
      type: text
      default: '0'
    douban_count:
      name: douban_count
      lable: douban_count
      type: text
      default: '100'
profile:
  label: 个人资料
  items:
    profile_enabled:
      name: profile_enabled
      label: profile_enabled
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    profile_author_description:
      name: profile_author_description
      label: 个人简介
      type: text
    profile_location:
      name: profile_location
      label: 地理位置
      type: text
    profile_follow:
      name: profile_follow
      label: profile_follow
      type: text
    profile_social_github:
      name: profile_social_github
      label: profile_social_github
      type: text
    profile_social_weibo:
      name: profile_social_weibo
      label: profile_social_weibo
      type: text
    profile_social_twitter:
      name: profile_social_twitter
      label: profile_social_twitter
      type: text
    profile_social_behance:
      name: profile_social_behance
      label: profile_social_behance
      type: text
    profile_social_rss:
      name: profile_social_rss
      label: profile_social_rss
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    profile_tooltip:
      name: profile_tooltip
      label: profile_tooltip
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭